### ISSUE TITLE
Algolia reindex issue

### ISSUE THREAD

**Issue by mihaj** [algolia/algoliasearch-rails#116]
I have a few models set up to use with algolia index.

Company model:

```
  algoliasearch per_environment: true, auto_index: false, auto_remove: false do
    attributes :name, :description, :permalink, :rank
    add_attribute :a_tags, :a_country, :a_image, :a_url, :a_location, :a_meta
    attributesToIndex ['name', 'a_tags', 'a_location']
    customRanking ['desc(rank)']
  end
...
```

Search Tag model:

```
  algoliasearch per_environment: true, auto_index: false, auto_remove: false do
    attributes :name
    add_attribute :a_search_tag_total_results
    add_attribute :a_url
    add_attribute :a_names
    attributesToIndex ['a_names']
    customRanking ['desc(a_search_tag_total_results)']
  end

  def a_search_tag_total_results
    self.counter
  end

  def a_url
    "/en/companies?keyword_search%5B%5D=#{self.name}"
  end

  def a_names
    {'en' => self.name}
  end
```

When I run Company.reindex! I get this error:

> NoMethodError: undefined method `a_search_tag_total_results' for #<Company:0x00000006eadea8>

Of course a_search_tag_total_results is not setup at Company but SearchTag. What am I missing?

Thanks!

Miha

**Comment by mihaj** [comment]
No ideas?

**Comment by alexandremeunier** [comment]
Hi @mihaj, we haven't been able to replicate the issue locally.

Could you provide us with the full error stack trace ? Are you using STIs ? Any additional information about your models would be helpful.

**Comment by mihaj** [comment]
Hi! What do you mean by STI? I will send you more details soon.

**Comment by mihaj** [comment]
```
A NoMethodError occurred in companies#update:

  undefined method `a_search_tag_total_results' for #<Company:0x007f8d15c4a7a8>
  app/controllers/account/companies_controller.rb:39:in `update'


-------------------------------
Request:
-------------------------------

  * URL        : 
  * HTTP Method: PATCH
  * IP address : 
  * Parameters : {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"ZTY+83VC0+MPn97rRFl+Gm4pfOUwZbppWrpl5KzMLLTffkmksXxYty3Q1CPLrM9asyOpYuRoAtLTjudPpSeF0A==", "company"=>{"name"=>"  Limited2", "permalink"=>"-b2b-limited", "vat"=>"6546", "id_number"=>"1733216", "website"=>"http://www.com", "description"=>"<p>.  lets Suppliers do more business. List your company for FREE to gain exposure to a world-wide audience. Just register - it's that simple.  lets your company shine when compliments come through &lsquo;the grapevine&rsquo;. Your company will be 'spotlighted' when clients / customers give praise when credit is due for your exceptional work and services. Our grapevine feedback system will create trust and build-up your image and reputation for your company and the business will grow naturally. &nbsp;</p>\r\n<ol>\r\n<li>test1</li>\r\n<li>test2</li>\r\n</ol>", "short_description"=>", Connecting Buyers and Sellers.", "detail"=>{"company_values"=>""}, "naics_codes"=>"", "detail_attributes"=>{"brands"=>"", "markets_served"=>"Global (Europe, Asia, America, Middle East and North Africa, East Asia and Pacific, Europe and Central Asia, Latin America and Caribbean, South Asia, Sub-Saharan Africa, North America, Western Europe, Australia, Asia)", "annual_sales"=>"", "certifications"=>"", "export_percentage"=>"", "environmental_merits"=>"Eco Friendly Environmentally Green", "established(1i)"=>"2012", "established(2i)"=>"1", "established(3i)"=>"1", "number_of_employees_id"=>"2", "id"=>"1"}}, "commit"=>"Save", "controller"=>"account/companies", "action"=>"update", "locale"=>"en", "id"=>"-b2b-limited"}
  * Timestamp  : 2016-06-15 11:39:31 +0200
  * Server : ..com
  * Rails root : /home
  * Process: 21843

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"return_to"=>"/en",
   "_csrf_token"=>"ukh3V8Q+i1QiTwrIj/WxQN0K1YfUDbi7iTSCqwnrqWQ=",
   "just_logged_in"=>true}

-------------------------------
Environment:
-------------------------------

  * CONTENT_LENGTH                              : 3858
  * CONTENT_TYPE                                : multipart/form-data; boundary=----WebKitFormBoundaryM5iDsgWKFoOMueqX
  * HTTPS                                       : on
  * HTTP_ACCEPT                                 : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                        : gzip, deflate, br
  * HTTP_ACCEPT_LANGUAGE                        : en-US,en;q=0.8
  * HTTP_AUTHORIZATION                          : Basic bWFuZ286clgwNjhFNGJoYmdQTDRHZEpxV0s=
  * HTTP_CACHE_CONTROL                          : max-age=0
  * HTTP_COOKIE                                 : __atuvc=0%7C16%2C0%7C17%2C0%7C18%2C7%7C19%2C1%7C20; __utma=77821320.98550595.1458688096.1464720342.1465880383.88; __utmc=77821320; __utmz=77821320.1458688096.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); currency=1; =f1bd870a1afbe22a631d4852df70b002; auth_token=3KNNC1dfWo9okgy4cFtbrw%3D%3D; current=1; time_zone=Europe/Berlin
  * HTTP_HOST                                   : ..com
  * HTTP_ORIGIN                                 : https://..com
  * HTTP_REFERER                                : h
  * HTTP_UPGRADE_INSECURE_REQUESTS              : 1
  * HTTP_USER_AGENT                             : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
  * HTTP_VERSION                                : HTTP/1.1
  * ORIGINAL_FULLPATH                           : 
  * ORIGINAL_SCRIPT_NAME                        :
  * PASSENGER_CONNECT_PASSWORD                  : [FILTERED]
  * PATH_INFO                                   : 
  * QUERY_STRING                                :
  * REMOTE_ADDR                                 : 
  * REMOTE_PORT                                 : 43564
  * REMOTE_USER                                 : 
  * REQUEST_METHOD                              : PATCH
  * REQUEST_URI                                 : /
  * ROUTES_31831180_SCRIPT_NAME                 :
  * SCRIPT_NAME                                 :
  * SERVER_NAME                                 : 
  * SERVER_PORT                                 : 443
  * SERVER_PROTOCOL                             : HTTP/1.1
  * SERVER_SOFTWARE                             : nginx/1.8.1 Phusion_Passenger/5.0.24
  * action_controller.instance                  : #<Account::CompaniesController:0x007f8d15d906a8>
  * action_dispatch.backtrace_cleaner           : #<Rails::BacktraceCleaner:0x000000009df990>
  * action_dispatch.cookies                     : #<ActionDispatch::Cookies::CookieJar:0x007f8d15d388e0>
  * action_dispatch.cookies_digest              :
  * action_dispatch.cookies_serializer          :
  * action_dispatch.encrypted_cookie_salt       : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt: signed encrypted cookie
  * action_dispatch.http_auth_salt              : http authentication
  * action_dispatch.key_generator               : #<ActiveSupport::CachingKeyGenerator:0x00000006ea04d8>
  * action_dispatch.logger                      : #<ActiveSupport::Logger:0x000000045b5ed8>
  * action_dispatch.parameter_filter            : [:password]
  * action_dispatch.redirect_filter             : []
  * action_dispatch.remote_ip                   : 
  * action_dispatch.request.content_type        : multipart/form-data
  * action_dispatch.request.formats             : [#<Mime::Type:0x000000020df500 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-4457937405581748205>]
  * action_dispatch.request.parameters          : {"utf8"=>"✓", "_method"=>"patch", 
  * action_dispatch.request_id                  : 11b06ca3-4dc9-460e-bab2-87e0e22e8744
  * action_dispatch.routes                      : #<ActionDispatch::Routing::RouteSet:0x00000003cb6918>
  * action_dispatch.secret_key_base             : nkt3DbSrlp7mkkeZijmbY7Ggw0rvMCykAx1HQzSpNyS8lLhQWQmSAPELIqwjchT5F9HaofPifLV3bam8B5UfPuWGsYtI4GuIqOCasapYJd76SrjOXcVbnmqewBPCBK
  * action_dispatch.secret_token                : nkt3DbSrlp7mkkeZijmbY7Ggw0rvMCykAx1HQzSpNyS8lLhQWQmSAPELIqwjchT5F9HaofPifLV3bam8B5UfPuWGsYtI4GuIqOCasapYJd76SrjOXcVbnmqewBPCBK
  * action_dispatch.show_detailed_exceptions    : false
  * action_dispatch.show_exceptions             : true
  * action_dispatch.signed_cookie_salt          : signed cookie
  * http_accept_language.parser                 : #<HttpAcceptLanguage::Parser:0x007f8d15dd4330>
  * rack.errors                                 : #<IO:0x000000006d5588>
  * rack.hijack                                 : #<Proc:0x007f8d15e3bb20@/usr/lib/ruby/1.8/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
  * rack.hijack?                                : true
  * rack.input                                  : #<PhusionPassenger::Utils::TeeInput:0x007f8d15e44180>
  * rack.methodoverride.original_method         : POST
  * rack.multiprocess                           : true
  * rack.multithread                            : false
  * rack.request.cookie_hash                    : {"__atuvc"=>"0|16,0|17,0|18,7|19,1|20", 
  * rack.request.form_input                     : #<PhusionPassenger::Utils::TeeInput:0x007f8d15e44180>
  * rack.request.query_hash                     : {}
  * rack.request.query_string                   :
  * rack.run_once                               : false
  * rack.session                                : #<ActionDispatch::Request::Session:0x007f8d15dd47e0>
  * rack.session.options                        : #<ActionDispatch::Request::Session::Options:0x007f8d15dd4718>
  * rack.session.record                         : #<ActiveRecord::SessionStore::Session:0x007f8d15d3a050>
  * rack.url_scheme                             : https
  * rack.version                                : [1, 2]

-------------------------------
Backtrace:
-------------------------------

  app/controllers/account/companies_controller.rb:39:in `update'
```

**Comment by mihaj** [comment]
This probably does not give you any clue? How can I get more detailed errors?

**Comment by alexandremeunier** [comment]
When you run `Company.reindex!` in the console does it give you a more detailed backtrace ? 

STI = Single Table Inheritance, see http://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html

**Comment by mihaj** [comment]
We dont use STI. Here is an error.

```
2.2.0 :001 > Company.reindex!
NoMethodError: undefined method `a_search_tag_total_results' for #<Company:0x00000006b3a168>
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:433:in `method_missing'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:93:in `block (2 levels) in add_attribute'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:115:in `call'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:115:in `block (2 levels) in get_attributes'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:115:in `each'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:115:in `block in get_attributes'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/scoping/default.rb:33:in `block in unscoped'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:302:in `scoping'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/scoping/default.rb:33:in `unscoped'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:112:in `get_attributes'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:410:in `block (3 levels) in algolia_reindex!'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:409:in `map'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:409:in `block (2 levels) in algolia_reindex!'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:124:in `find_in_batches'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/querying.rb:9:in `find_in_batches'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:738:in `algolia_find_in_batches'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:401:in `block in algolia_reindex!'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:395:in `each'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:395:in `algolia_reindex!'
	from (irb):1
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/mango/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
```

**Comment by redox** [comment]
I'm digging into that right now; the sta

**Comment by redox** [comment]
I'm digging into that right now; the behavior is so weird :/

**Comment by mihaj** [comment]
OK, so any news about this?

**Comment by redox** [comment]
> OK, so any news about this?

Unfortunately, I cannot reproduce such issue on my side. Are you able to reproduce it in a dummy app so we could iterate?

**Comment by mihaj** [comment]
Can you give me your email, so we can move this chat to a private one, since I will share some critical details..

**Comment by alexandremeunier** [comment]
You can send the email with additional details to support@algolia.com.
On Thu, 23 Jun 2016 at 10:43, Miha Jakovac <notifications@github.com> wrote:

> Can you give me your email, so we can move this chat to a private one,
> since I will share some critical details..
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/algolia/algoliasearch-rails/issues/116#issuecomment-227986617>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA6sJRd9uuOe7pTKiCs3uBHHXVXJ0eKNks5qOkclgaJpZM4InubC>
> .
>
-- 
--

<https://www.algolia.com/>

  <https://twitter.com/dephadepha>
<https://uk.linkedin.com/pub/alexandre-meunier/13/227/a2>
<https://github.com/alexandremeunier>

Alexandre Meunier
Software Engineer

Phone: +33 6 81 81 94 33
Website: algolia.com <https://www.algolia.com/#millisecond-matter>
<https://www.algolia.com/#milliseconds-matter>

We are hiring! <https://www.algolia.com/jobs#milliseconds-matter>

**Comment by mihaj** [comment]
The problem was, that the 

> include AlgoliaSearch

 was not inside the class but outside.

Correct:
```
class SearchTag < ActiveRecord::Base
    include AlgoliaSearch
end
```

Wrong:
```
include AlgoliaSearch
class SearchTag < ActiveRecord::Base

end
```

**Comment by redox** [comment]
Oh wow /o\ @mihaj Thank you for sharing us with that. I think we could add a check to ensure the parent class is something we support.
