### ISSUE TITLE
reindex causing errors

### ISSUE THREAD

**Issue by chadwtaylor** [algolia/algoliasearch-rails#127]
When I do a `reindex`, it throws an error: `NoMethodError: undefined method 'additional_indexes' for nil:NilClass`.

Am using the `1.14.1` version.

Here's the output of my console:

```
> Person.reindex
NoMethodError: undefined method `additional_indexes' for nil:NilClass
       	from /Users/xx/.gem/ruby/2.3.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:643:in `algolia_configurations'
       	from /Users/xx/.gem/ruby/2.3.0/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb:426:in `algolia_reindex'
       	from (irb):8
       	from /Users/xx/.gem/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
       	from /Users/xx/.gem/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
       	from /Users/xx/.gem/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
       	from /Users/xx/.gem/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
       	from /Users/xx/.gem/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
       	from bin/rails:4:in `require'
       	from bin/rails:4:in `<main>'
```

**Comment by thornomad** [comment]
+1 - experiencing the same issue.

**Comment by matthieua** [comment]
Same here :(

**Comment by redox** [comment]
Sorry for the late reply guys. I'll try to reproduce it, that's weird :/

**Comment by matthieua** [comment]
Here is the stack trace:
```ruby
Failure/Error: ::Post.reindex!

NoMethodError:
  undefined method `additional_indexes' for nil:NilClass
# /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:662:in `algolia_configurations'
# /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:411:in `algolia_reindex!'
```

**Comment by redox** [comment]
> I found this issue, the algoliasearch block wasn't defined on my model when running the tests, it works fine now for me.

Thanks for the heads up @matthieua; was definitely the issue. I added a new exception + 1 test around that to make sure it's clearer.
