### ISSUE TITLE
Using say in utilities.rb prevents using the method in a rake task

### ISSUE THREAD

**Issue by parterburn** [algolia/algoliasearch-rails#232]
Is it possible to swap out the `say` in `utilities.rb` with `puts`? It looks like this is ideal for running the command in migrations, put preventing it from being used in rake tasks.

The error I get when trying to run `alogoliasearch:reindex` on a fairly simple Heroku app:

```
NoMethodError: undefined method `say' for AlgoliaSearch::Utilities:Module
/app/vendor/bundle/ruby/2.3.0/gems/algoliasearch-rails-1.19.1/lib/algoliasearch/utilities.rb:23:in `block in reindex_all_models'
/app/vendor/bundle/ruby/2.3.0/gems/algoliasearch-rails-1.19.1/lib/algoliasearch/utilities.rb:22:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/algoliasearch-rails-1.19.1/lib/algoliasearch/utilities.rb:22:in `reindex_all_models'
/app/vendor/bundle/ruby/2.3.0/gems/algoliasearch-rails-1.19.1/lib/algoliasearch/tasks/algoliasearch.rake:5:in `block (2 levels) in <top (required)>'
```

**Comment by parterburn** [comment]
@redox thoughts on this one? We're hitting errors in rake tasks + seeds.rb with the current setup.

**Comment by EricInflect** [comment]
hitting this as well

**Comment by redox** [comment]
Arg, not sure what that was; will go for regular `puts`.
