### ISSUE TITLE
NoMethodError: undefined method `*' for nil:NilClass

### ISSUE THREAD

**Issue by cupofjoakim** [algolia/algoliasearch-rails#242]
It's getting thrown around in my tests a lot and I can't figure out why. It feels like I'm missing something obvious, but I don't know what.

Here's the backtrace:

```
Failure/Error: @users = User.search(search_string, { tagFilters: [garage_filter] })

NoMethodError:
            undefined method `*' for nil:NilClass
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/algoliasearch-rails-1.19.1/lib/algoliasearch-rails.rb:659:in `algolia_search'
          # ./app/controllers/search_controller.rb:18:in `index'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:188:in `process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:126:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:455:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/rescue.rb:20:in `process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:126:in `process'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0/lib/action_view/rendering.rb:30:in `process'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal.rb:190:in `dispatch'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal.rb:262:in `dispatch'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:32:in `serve'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/journey/router.rb:39:in `block in serve'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/journey/router.rb:26:in `each'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/journey/router.rb:26:in `serve'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:725:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bullet-5.1.1/lib/bullet/rack.rb:10:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/cookies.rb:613:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in `call_app'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `block in call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:70:in `block in tagged'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:26:in `tagged'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:70:in `tagged'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/request_id.rb:24:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/static.rb:136:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/font_assets-0.1.12/lib/font_assets/middleware.rb:29:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sentry-raven-2.4.0/lib/raven/integrations/rack.rb:50:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/server.rb:43:in `call'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
          # /Users/wimmerstedt/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

And here's the only algolia things I've got in my model (except the algolia inclusion):

```
algoliasearch do
    attribute :first_name, :last_name, :email, :phone
    searchableAttributes ['first_name', 'last_name', 'email', 'phone']
    tags do
      garage_tags
    end
 end
```

Where garage_tags is an array of strings like `garage_#{garage.id}`.

**Comment by redox** [comment]
Could you also tell us how you configure the overall account? Any chance you enabled `will_paginate` or `kaminari` in your `config/initializers/algolia.rb` ?

**Comment by cupofjoakim** [comment]
@redox What do you mean by the account question? It's a standard account on algolia?

My config is the base config, i.e. `AlgoliaSearch.configuration = { application_id: 'myID', api_key: 'myAPIKey' }`, so I'm not enabling any pagination or kaminari.

**Comment by cupofjoakim** [comment]
Note that this happens when running tests, I'm not getting any raised errors when developing. Is it an issue with rspec or the test environment?

**Comment by cupofjoakim** [comment]
@redox I'm using the stubs from algolia/webmock!

**Comment by cupofjoakim** [comment]
@redox Any idea what this was about?

**Comment by redox** [comment]
@cupofjoakim right; I finally found the time to look at it. Indeed if the API answer is mocked, an internal multiplication will fail. Fixing it now.

**Comment by cupofjoakim** [comment]
@redox THANK YOU! 

![fuck yeah](http://replygif.net/i/1309.gif)
