### ISSUE TITLE
Mongoid Cursor Timeout

### ISSUE THREAD

**Issue by hcurotta** [algolia/algoliasearch-rails#29]
When iterating over large collections, the Mongoid cursor will timeout after 10 minutes. 

Example error below:

```
irb(main):002:0> Member.reindex!
Moped::Errors::CursorNotFound: The operation: "GET MORE"
failed with error "cursor 3213467116051329994 not found"
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/moped-1.5.1/lib/moped/node.rb:216:in `get_more'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/moped-1.5.1/lib/moped/cursor.rb:44:in `get_more'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/moped-1.5.1/lib/moped/cursor.rb:29:in `each'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/moped-1.5.1/lib/moped/query.rb:76:in `each'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/moped-1.5.1/lib/moped/query.rb:76:in `each'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/mongoid-3.1.5/lib/mongoid/contextual/mongo.rb:122:in `block in each'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/mongoid-3.1.5/lib/mongoid/contextual/mongo.rb:619:in `selecting'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/mongoid-3.1.5/lib/mongoid/contextual/mongo.rb:121:in `each'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/mongoid-3.1.5/lib/mongoid/contextual.rb:19:in `each'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/algoliasearch-rails-1.11.7/lib/algoliasearch-rails.rb:569:in `algolia_find_in_batches'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/algoliasearch-rails-1.11.7/lib/algoliasearch-rails.rb:237:in `block in algolia_reindex!'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/algoliasearch-rails-1.11.7/lib/algoliasearch-rails.rb:231:in `each'
	from /var/www/imagebrief/dev/shared/bundle/ruby/1.9.1/gems/algoliasearch-rails-1.11.7/lib/algoliasearch-rails.rb:231:in `algolia_reindex!'
```

**Comment by redox** [comment]
Closing this for now; feel free to re-open if we know more.
