### ISSUE TITLE
An error was encountered. NoMethodError: undefined method `count 'for nil: NilClass during algoliasearch: reindex task

### ISSUE THREAD

**Issue by kaito0228** [algolia/algoliasearch-rails#366]
- Rails version: 6.0.0
- Algolia Rails integration version: 1.23.2
- Algolia Client Version: 1.27.0
- Language Version: 2.6.3

### Description
An error was encountered while running the algoliasearch:reindex task.
algoliasearch-rails is applied to two models.

```
NoMethodError: undefined method `count' for nil:NilClass
/app/vendor/bundle/ruby/2.6.0/gems/algoliasearch-rails-1.23.2/lib/algoliasearch/utilities.rb:19:in `reindex_all_models'
/app/vendor/bundle/ruby/2.6.0/gems/algoliasearch-rails-1.23.2/lib/algoliasearch/tasks/algoliasearch.rake:5:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/app/vendor/bundle/bin/bundle:104:in `load'
/app/vendor/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => algoliasearch:reindex
(See full trace by running task with --trace)
```

It will succeed if it is executed for each model as shown below.
`Model_name.reindex`

I guess, task seems to have failed since upgrading from rails 5.2.3 to 6.0.0.

### Steps To Reproduce
Prepare a model using algoliasearch-rails.
Run the algoliasearch:reindex task.

**Comment by chaadow** [comment]
@kaito0228  This should be fixed in an upcoming version (patch or minor) of rails 6, I guess you're having this issue in the `development` environment,  If you need a quick fix, just put this snippet of code in an initializer:
```rb
module AlgoliaSearch
  module Utilities
    class << self
      def get_model_classes
        Zeitwerk::Loader.eager_load_all # instead of  Rails.application.eager_load!
        AlgoliaSearch.instance_variable_get :@included_in
      end
   end
end
```

**Comment by chaadow** [comment]
Also there is a PR for this #364

**Comment by kaito0228** [comment]
@chaadow 
OK. I see.
Thanks for your announcement.

**Comment by masudhossain** [comment]
Bump. 

I'm getting same error again. I have `gem 'rails', '~> 5.0.2'` and `algoliasearch (1.27.5)`.
