### ISSUE TITLE
Support for faraday version > 2

### ISSUE THREAD

**Issue by QuentinRoadstr** [algolia/algoliasearch-rails#442]
Hi, is support for faraday version 2 planned ?

I meet this error with 

> ruby "3.3.0"
> gem "rails", "7.1.3"
> gem "algoliasearch-rails"
> gem "faraday"

in Gemfile

> /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:7:in `<class:NetHttpPersistent>': undefined method `dependency' for class Faraday::Adapter::NetHttpPersistent (NoMethodError)
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:6:in `<class:Adapter>'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:4:in `<module:Faraday>'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:3:in `<main>'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/net_http_persistent.rb:3:in `require_relative'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/net_http_persistent.rb:3:in `<main>'
> 	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
> 	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/algolia-2.3.4/lib/algolia/transport/transport.rb:3:in `<main>'
> 	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
> 	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/algolia-2.3.4/lib/algolia.rb:31:in `<main>'
> 	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
> 	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
> 	from /home/runner/work/roadstr-app/roadstr-app/vendor/bundle/ruby/3.3.0/gems/algoliasearch-rails-2.3.1/lib/algoliasearch-rails.rb:1:in `<main>'

**Comment by QuentinRoadstr** [comment]
There is more information about this error here
https://github.com/lostisland/faraday_middleware/issues/280#issuecomment-1049630695
